[platformio]
default_envs = esp32dev
src_dir = firmware/motorcycle_slot

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  zinggjm/GxEPD2@^1.6.5
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO
lib_ldf_mode = deep+
