#!/usr/bin/env python3
"""Crop motorcycle art to a 1-bit sprite and emit a GxEPD2/Adafruit GFX C array."""

from __future__ import annotations

import os
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(ROOT, "assets", "pixel", "src")
OUT_PNG = os.path.join(ROOT, "assets", "pixel", "1bit")
OUT_HDR = os.path.join(ROOT, "firmware", "motorcycle_slot", "bitmaps.h")

SPRITE_W = 112  # multiple of 8
SPRITE_H = 80

# (filename without ext, C symbol)
SPRITES = [
    ("r7", "bmp_r7"),
    ("r9", "bmp_r9"),
    ("tt", "bmp_tt"),
    ("hs", "bmp_hs"),
    ("jp", "bmp_jp"),
]


def load_src(stem: str) -> Image.Image:
    for ext in (".png", ".jpg", ".jpeg"):
        path = os.path.join(SRC, stem + ext)
        if os.path.isfile(path):
            return Image.open(path).convert("RGB")
    raise FileNotFoundError(stem)


def ink(rgb: Image.Image, thresh: int = 200) -> Image.Image:
    """Dark ink on white. 0 = black in the returned mode-L image."""
    g = rgb.convert("L")
    return g.point(lambda p: 0 if p < thresh else 255)


def bbox(mask: Image.Image) -> tuple[int, int, int, int]:
    ext = mask.getbbox()
    if ext is None:
        raise RuntimeError("empty mask")
    return ext


def fit_1bit(ink_img: Image.Image) -> Image.Image:
    # bbox of ink (black)
    inv = ink_img.point(lambda p: 255 - p)
    x0, y0, x1, y1 = bbox(inv)
    pad = 6
    x0 = max(0, x0 - pad)
    y0 = max(0, y0 - pad)
    x1 = min(ink_img.width, x1 + pad)
    y1 = min(ink_img.height, y1 + pad)
    crop = ink_img.crop((x0, y0, x1, y1))

    scale = min(SPRITE_W / crop.width, SPRITE_H / crop.height)
    nw = max(1, int(crop.width * scale))
    nh = max(1, int(crop.height * scale))
    resized = crop.resize((nw, nh), Image.Resampling.NEAREST)

    canvas = Image.new("1", (SPRITE_W, SPRITE_H), 1)  # white
    bike = resized.convert("1")
    ox = (SPRITE_W - nw) // 2
    oy = (SPRITE_H - nh) // 2
    canvas.paste(bike, (ox, oy))
    return canvas


def pack_bytes(im: Image.Image) -> list[int]:
    w, h = im.size
    pix = im.load()
    row_bytes = (w + 7) // 8
    out: list[int] = []
    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and pix[x, y] == 0:
                    byte |= 0x80 >> bit
            out.append(byte)
    return out


def c_array(name: str, data: list[int], w: int, h: int) -> str:
    lines = [f"const unsigned char {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append(f"const uint16_t {name}_w = {w};")
    lines.append(f"const uint16_t {name}_h = {h};")
    return "\n".join(lines)


def main() -> None:
    os.makedirs(OUT_PNG, exist_ok=True)
    blocks = []
    for stem, symbol in SPRITES:
        rgb = load_src(stem)
        sprite = fit_1bit(ink(rgb))
        png_path = os.path.join(OUT_PNG, f"{stem}.png")
        sprite.save(png_path)
        preview = sprite.convert("L").resize((SPRITE_W * 4, SPRITE_H * 4), Image.Resampling.NEAREST)
        preview.save(os.path.join(OUT_PNG, f"{stem}_x4.png"))
        data = pack_bytes(sprite)
        blocks.append(c_array(symbol, data, SPRITE_W, SPRITE_H))
        black = sum(1 for p in sprite.getdata() if p == 0)
        print(f"{stem}: {sprite.size}  black={black}")

    header = """#pragma once
#include <Arduino.h>
#include <avr/pgmspace.h>

// 1-bit side-view sprites, 112x80, MSB-left. 1 = black.
// Regenerated by tools/png_to_bitmap.py

#ifdef ESP32
#include <pgmspace.h>
#endif

"""
    # ESP32 Arduino uses pgmspace.h from pgmspace, not avr. Avoid avr include.
    header = """#pragma once
#include <Arduino.h>

// 1-bit side-view sprites, 112x80, MSB-left. 1 = black.
// Regenerated by tools/png_to_bitmap.py

"""
    text = header + "\n\n".join(blocks) + "\n"
    os.makedirs(os.path.dirname(OUT_HDR), exist_ok=True)
    with open(OUT_HDR, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print("wrote", OUT_HDR)


if __name__ == "__main__":
    main()
